-- FrontOffice Build 13E fix
-- Seed and normalize every supported NBA, NFL, MLB, and Premier League team.
--
-- Migration 017 only updated rows where league was already populated.
-- The current starter teams table has NULL league values and only a small subset,
-- so that UPDATE could succeed while matching zero rows.

with supported_teams(name, sport, league, abbreviation, provider_key) as (
values
  ('Atlanta Hawks', 'NBA', 'NBA', 'ATL', 'atl'),
  ('Boston Celtics', 'NBA', 'NBA', 'BOS', 'bos'),
  ('Brooklyn Nets', 'NBA', 'NBA', 'BKN', 'bkn'),
  ('Charlotte Hornets', 'NBA', 'NBA', 'CHA', 'cha'),
  ('Chicago Bulls', 'NBA', 'NBA', 'CHI', 'chi'),
  ('Cleveland Cavaliers', 'NBA', 'NBA', 'CLE', 'cle'),
  ('Dallas Mavericks', 'NBA', 'NBA', 'DAL', 'dal'),
  ('Denver Nuggets', 'NBA', 'NBA', 'DEN', 'den'),
  ('Detroit Pistons', 'NBA', 'NBA', 'DET', 'det'),
  ('Golden State Warriors', 'NBA', 'NBA', 'GSW', 'gsw'),
  ('Houston Rockets', 'NBA', 'NBA', 'HOU', 'hou'),
  ('Indiana Pacers', 'NBA', 'NBA', 'IND', 'ind'),
  ('LA Clippers', 'NBA', 'NBA', 'LAC', 'lac'),
  ('Los Angeles Lakers', 'NBA', 'NBA', 'LAL', 'lal'),
  ('Memphis Grizzlies', 'NBA', 'NBA', 'MEM', 'mem'),
  ('Miami Heat', 'NBA', 'NBA', 'MIA', 'mia'),
  ('Milwaukee Bucks', 'NBA', 'NBA', 'MIL', 'mil'),
  ('Minnesota Timberwolves', 'NBA', 'NBA', 'MIN', 'min'),
  ('New Orleans Pelicans', 'NBA', 'NBA', 'NOP', 'nop'),
  ('New York Knicks', 'NBA', 'NBA', 'NYK', 'nyk'),
  ('Oklahoma City Thunder', 'NBA', 'NBA', 'OKC', 'okc'),
  ('Orlando Magic', 'NBA', 'NBA', 'ORL', 'orl'),
  ('Philadelphia 76ers', 'NBA', 'NBA', 'PHI', 'phi'),
  ('Phoenix Suns', 'NBA', 'NBA', 'PHX', 'phx'),
  ('Portland Trail Blazers', 'NBA', 'NBA', 'POR', 'por'),
  ('Sacramento Kings', 'NBA', 'NBA', 'SAC', 'sac'),
  ('San Antonio Spurs', 'NBA', 'NBA', 'SAS', 'sas'),
  ('Toronto Raptors', 'NBA', 'NBA', 'TOR', 'tor'),
  ('Utah Jazz', 'NBA', 'NBA', 'UTA', 'uta'),
  ('Washington Wizards', 'NBA', 'NBA', 'WAS', 'was'),
  ('Arizona Cardinals', 'NFL', 'NFL', 'ARI', 'ari'),
  ('Atlanta Falcons', 'NFL', 'NFL', 'ATL', 'atl'),
  ('Baltimore Ravens', 'NFL', 'NFL', 'BAL', 'bal'),
  ('Buffalo Bills', 'NFL', 'NFL', 'BUF', 'buf'),
  ('Carolina Panthers', 'NFL', 'NFL', 'CAR', 'car'),
  ('Chicago Bears', 'NFL', 'NFL', 'CHI', 'chi'),
  ('Cincinnati Bengals', 'NFL', 'NFL', 'CIN', 'cin'),
  ('Cleveland Browns', 'NFL', 'NFL', 'CLE', 'cle'),
  ('Dallas Cowboys', 'NFL', 'NFL', 'DAL', 'dal'),
  ('Denver Broncos', 'NFL', 'NFL', 'DEN', 'den'),
  ('Detroit Lions', 'NFL', 'NFL', 'DET', 'det'),
  ('Green Bay Packers', 'NFL', 'NFL', 'GB', 'gb'),
  ('Houston Texans', 'NFL', 'NFL', 'HOU', 'hou'),
  ('Indianapolis Colts', 'NFL', 'NFL', 'IND', 'ind'),
  ('Jacksonville Jaguars', 'NFL', 'NFL', 'JAX', 'jax'),
  ('Kansas City Chiefs', 'NFL', 'NFL', 'KC', 'kc'),
  ('Las Vegas Raiders', 'NFL', 'NFL', 'LV', 'lv'),
  ('Los Angeles Chargers', 'NFL', 'NFL', 'LAC', 'lac'),
  ('Los Angeles Rams', 'NFL', 'NFL', 'LAR', 'lar'),
  ('Miami Dolphins', 'NFL', 'NFL', 'MIA', 'mia'),
  ('Minnesota Vikings', 'NFL', 'NFL', 'MIN', 'min'),
  ('New England Patriots', 'NFL', 'NFL', 'NE', 'ne'),
  ('New Orleans Saints', 'NFL', 'NFL', 'NO', 'no'),
  ('New York Giants', 'NFL', 'NFL', 'NYG', 'nyg'),
  ('New York Jets', 'NFL', 'NFL', 'NYJ', 'nyj'),
  ('Philadelphia Eagles', 'NFL', 'NFL', 'PHI', 'phi'),
  ('Pittsburgh Steelers', 'NFL', 'NFL', 'PIT', 'pit'),
  ('San Francisco 49ers', 'NFL', 'NFL', 'SF', 'sf'),
  ('Seattle Seahawks', 'NFL', 'NFL', 'SEA', 'sea'),
  ('Tampa Bay Buccaneers', 'NFL', 'NFL', 'TB', 'tb'),
  ('Tennessee Titans', 'NFL', 'NFL', 'TEN', 'ten'),
  ('Washington Commanders', 'NFL', 'NFL', 'WAS', 'was'),
  ('Arsenal', 'SOCCER', 'Premier League', 'ARS', 'ars'),
  ('Aston Villa', 'SOCCER', 'Premier League', 'AVL', 'avl'),
  ('Bournemouth', 'SOCCER', 'Premier League', 'BOU', 'bou'),
  ('Brentford', 'SOCCER', 'Premier League', 'BRE', 'bre'),
  ('Brighton & Hove Albion', 'SOCCER', 'Premier League', 'BHA', 'bha'),
  ('Chelsea', 'SOCCER', 'Premier League', 'CHE', 'che'),
  ('Crystal Palace', 'SOCCER', 'Premier League', 'CRY', 'cry'),
  ('Everton', 'SOCCER', 'Premier League', 'EVE', 'eve'),
  ('Fulham', 'SOCCER', 'Premier League', 'FUL', 'ful'),
  ('Liverpool', 'SOCCER', 'Premier League', 'LIV', 'liv'),
  ('Manchester City', 'SOCCER', 'Premier League', 'MCI', 'mci'),
  ('Manchester United', 'SOCCER', 'Premier League', 'MUN', 'mun'),
  ('Newcastle United', 'SOCCER', 'Premier League', 'NEW', 'new'),
  ('Nottingham Forest', 'SOCCER', 'Premier League', 'NFO', 'nfo'),
  ('Sunderland', 'SOCCER', 'Premier League', 'SUN', 'sun'),
  ('Tottenham Hotspur', 'SOCCER', 'Premier League', 'TOT', 'tot'),
  ('West Ham United', 'SOCCER', 'Premier League', 'WHU', 'whu'),
  ('Wolverhampton Wanderers', 'SOCCER', 'Premier League', 'WOL', 'wol'),
  ('Leeds United', 'SOCCER', 'Premier League', 'LEE', 'lee'),
  ('Burnley', 'SOCCER', 'Premier League', 'BUR', 'bur'),
  ('Arizona Diamondbacks', 'MLB', 'MLB', 'ARI', 'ari'),
  ('Atlanta Braves', 'MLB', 'MLB', 'ATL', 'atl'),
  ('Baltimore Orioles', 'MLB', 'MLB', 'BAL', 'bal'),
  ('Boston Red Sox', 'MLB', 'MLB', 'BOS', 'bos'),
  ('Chicago Cubs', 'MLB', 'MLB', 'CHC', 'chc'),
  ('Chicago White Sox', 'MLB', 'MLB', 'CWS', 'cws'),
  ('Cincinnati Reds', 'MLB', 'MLB', 'CIN', 'cin'),
  ('Cleveland Guardians', 'MLB', 'MLB', 'CLE', 'cle'),
  ('Colorado Rockies', 'MLB', 'MLB', 'COL', 'col'),
  ('Detroit Tigers', 'MLB', 'MLB', 'DET', 'det'),
  ('Houston Astros', 'MLB', 'MLB', 'HOU', 'hou'),
  ('Kansas City Royals', 'MLB', 'MLB', 'KC', 'kc'),
  ('Los Angeles Angels', 'MLB', 'MLB', 'LAA', 'laa'),
  ('Los Angeles Dodgers', 'MLB', 'MLB', 'LAD', 'lad'),
  ('Miami Marlins', 'MLB', 'MLB', 'MIA', 'mia'),
  ('Milwaukee Brewers', 'MLB', 'MLB', 'MIL', 'mil'),
  ('Minnesota Twins', 'MLB', 'MLB', 'MIN', 'min'),
  ('New York Mets', 'MLB', 'MLB', 'NYM', 'nym'),
  ('New York Yankees', 'MLB', 'MLB', 'NYY', 'nyy'),
  ('Athletics', 'MLB', 'MLB', 'ATH', 'ath'),
  ('Philadelphia Phillies', 'MLB', 'MLB', 'PHI', 'phi'),
  ('Pittsburgh Pirates', 'MLB', 'MLB', 'PIT', 'pit'),
  ('San Diego Padres', 'MLB', 'MLB', 'SD', 'sd'),
  ('San Francisco Giants', 'MLB', 'MLB', 'SF', 'sf'),
  ('Seattle Mariners', 'MLB', 'MLB', 'SEA', 'sea'),
  ('St. Louis Cardinals', 'MLB', 'MLB', 'STL', 'stl'),
  ('Tampa Bay Rays', 'MLB', 'MLB', 'TB', 'tb'),
  ('Texas Rangers', 'MLB', 'MLB', 'TEX', 'tex'),
  ('Toronto Blue Jays', 'MLB', 'MLB', 'TOR', 'tor'),
  ('Washington Nationals', 'MLB', 'MLB', 'WAS', 'was')
)
update public.teams as teams
set
  sport = supported.sport,
  league = supported.league,
  abbreviation = supported.abbreviation,
  provider_key = supported.provider_key
from supported_teams as supported
where lower(teams.name) = lower(supported.name);

with supported_teams(name, sport, league, abbreviation, provider_key) as (
values
  ('Atlanta Hawks', 'NBA', 'NBA', 'ATL', 'atl'),
  ('Boston Celtics', 'NBA', 'NBA', 'BOS', 'bos'),
  ('Brooklyn Nets', 'NBA', 'NBA', 'BKN', 'bkn'),
  ('Charlotte Hornets', 'NBA', 'NBA', 'CHA', 'cha'),
  ('Chicago Bulls', 'NBA', 'NBA', 'CHI', 'chi'),
  ('Cleveland Cavaliers', 'NBA', 'NBA', 'CLE', 'cle'),
  ('Dallas Mavericks', 'NBA', 'NBA', 'DAL', 'dal'),
  ('Denver Nuggets', 'NBA', 'NBA', 'DEN', 'den'),
  ('Detroit Pistons', 'NBA', 'NBA', 'DET', 'det'),
  ('Golden State Warriors', 'NBA', 'NBA', 'GSW', 'gsw'),
  ('Houston Rockets', 'NBA', 'NBA', 'HOU', 'hou'),
  ('Indiana Pacers', 'NBA', 'NBA', 'IND', 'ind'),
  ('LA Clippers', 'NBA', 'NBA', 'LAC', 'lac'),
  ('Los Angeles Lakers', 'NBA', 'NBA', 'LAL', 'lal'),
  ('Memphis Grizzlies', 'NBA', 'NBA', 'MEM', 'mem'),
  ('Miami Heat', 'NBA', 'NBA', 'MIA', 'mia'),
  ('Milwaukee Bucks', 'NBA', 'NBA', 'MIL', 'mil'),
  ('Minnesota Timberwolves', 'NBA', 'NBA', 'MIN', 'min'),
  ('New Orleans Pelicans', 'NBA', 'NBA', 'NOP', 'nop'),
  ('New York Knicks', 'NBA', 'NBA', 'NYK', 'nyk'),
  ('Oklahoma City Thunder', 'NBA', 'NBA', 'OKC', 'okc'),
  ('Orlando Magic', 'NBA', 'NBA', 'ORL', 'orl'),
  ('Philadelphia 76ers', 'NBA', 'NBA', 'PHI', 'phi'),
  ('Phoenix Suns', 'NBA', 'NBA', 'PHX', 'phx'),
  ('Portland Trail Blazers', 'NBA', 'NBA', 'POR', 'por'),
  ('Sacramento Kings', 'NBA', 'NBA', 'SAC', 'sac'),
  ('San Antonio Spurs', 'NBA', 'NBA', 'SAS', 'sas'),
  ('Toronto Raptors', 'NBA', 'NBA', 'TOR', 'tor'),
  ('Utah Jazz', 'NBA', 'NBA', 'UTA', 'uta'),
  ('Washington Wizards', 'NBA', 'NBA', 'WAS', 'was'),
  ('Arizona Cardinals', 'NFL', 'NFL', 'ARI', 'ari'),
  ('Atlanta Falcons', 'NFL', 'NFL', 'ATL', 'atl'),
  ('Baltimore Ravens', 'NFL', 'NFL', 'BAL', 'bal'),
  ('Buffalo Bills', 'NFL', 'NFL', 'BUF', 'buf'),
  ('Carolina Panthers', 'NFL', 'NFL', 'CAR', 'car'),
  ('Chicago Bears', 'NFL', 'NFL', 'CHI', 'chi'),
  ('Cincinnati Bengals', 'NFL', 'NFL', 'CIN', 'cin'),
  ('Cleveland Browns', 'NFL', 'NFL', 'CLE', 'cle'),
  ('Dallas Cowboys', 'NFL', 'NFL', 'DAL', 'dal'),
  ('Denver Broncos', 'NFL', 'NFL', 'DEN', 'den'),
  ('Detroit Lions', 'NFL', 'NFL', 'DET', 'det'),
  ('Green Bay Packers', 'NFL', 'NFL', 'GB', 'gb'),
  ('Houston Texans', 'NFL', 'NFL', 'HOU', 'hou'),
  ('Indianapolis Colts', 'NFL', 'NFL', 'IND', 'ind'),
  ('Jacksonville Jaguars', 'NFL', 'NFL', 'JAX', 'jax'),
  ('Kansas City Chiefs', 'NFL', 'NFL', 'KC', 'kc'),
  ('Las Vegas Raiders', 'NFL', 'NFL', 'LV', 'lv'),
  ('Los Angeles Chargers', 'NFL', 'NFL', 'LAC', 'lac'),
  ('Los Angeles Rams', 'NFL', 'NFL', 'LAR', 'lar'),
  ('Miami Dolphins', 'NFL', 'NFL', 'MIA', 'mia'),
  ('Minnesota Vikings', 'NFL', 'NFL', 'MIN', 'min'),
  ('New England Patriots', 'NFL', 'NFL', 'NE', 'ne'),
  ('New Orleans Saints', 'NFL', 'NFL', 'NO', 'no'),
  ('New York Giants', 'NFL', 'NFL', 'NYG', 'nyg'),
  ('New York Jets', 'NFL', 'NFL', 'NYJ', 'nyj'),
  ('Philadelphia Eagles', 'NFL', 'NFL', 'PHI', 'phi'),
  ('Pittsburgh Steelers', 'NFL', 'NFL', 'PIT', 'pit'),
  ('San Francisco 49ers', 'NFL', 'NFL', 'SF', 'sf'),
  ('Seattle Seahawks', 'NFL', 'NFL', 'SEA', 'sea'),
  ('Tampa Bay Buccaneers', 'NFL', 'NFL', 'TB', 'tb'),
  ('Tennessee Titans', 'NFL', 'NFL', 'TEN', 'ten'),
  ('Washington Commanders', 'NFL', 'NFL', 'WAS', 'was'),
  ('Arsenal', 'SOCCER', 'Premier League', 'ARS', 'ars'),
  ('Aston Villa', 'SOCCER', 'Premier League', 'AVL', 'avl'),
  ('Bournemouth', 'SOCCER', 'Premier League', 'BOU', 'bou'),
  ('Brentford', 'SOCCER', 'Premier League', 'BRE', 'bre'),
  ('Brighton & Hove Albion', 'SOCCER', 'Premier League', 'BHA', 'bha'),
  ('Chelsea', 'SOCCER', 'Premier League', 'CHE', 'che'),
  ('Crystal Palace', 'SOCCER', 'Premier League', 'CRY', 'cry'),
  ('Everton', 'SOCCER', 'Premier League', 'EVE', 'eve'),
  ('Fulham', 'SOCCER', 'Premier League', 'FUL', 'ful'),
  ('Liverpool', 'SOCCER', 'Premier League', 'LIV', 'liv'),
  ('Manchester City', 'SOCCER', 'Premier League', 'MCI', 'mci'),
  ('Manchester United', 'SOCCER', 'Premier League', 'MUN', 'mun'),
  ('Newcastle United', 'SOCCER', 'Premier League', 'NEW', 'new'),
  ('Nottingham Forest', 'SOCCER', 'Premier League', 'NFO', 'nfo'),
  ('Sunderland', 'SOCCER', 'Premier League', 'SUN', 'sun'),
  ('Tottenham Hotspur', 'SOCCER', 'Premier League', 'TOT', 'tot'),
  ('West Ham United', 'SOCCER', 'Premier League', 'WHU', 'whu'),
  ('Wolverhampton Wanderers', 'SOCCER', 'Premier League', 'WOL', 'wol'),
  ('Leeds United', 'SOCCER', 'Premier League', 'LEE', 'lee'),
  ('Burnley', 'SOCCER', 'Premier League', 'BUR', 'bur'),
  ('Arizona Diamondbacks', 'MLB', 'MLB', 'ARI', 'ari'),
  ('Atlanta Braves', 'MLB', 'MLB', 'ATL', 'atl'),
  ('Baltimore Orioles', 'MLB', 'MLB', 'BAL', 'bal'),
  ('Boston Red Sox', 'MLB', 'MLB', 'BOS', 'bos'),
  ('Chicago Cubs', 'MLB', 'MLB', 'CHC', 'chc'),
  ('Chicago White Sox', 'MLB', 'MLB', 'CWS', 'cws'),
  ('Cincinnati Reds', 'MLB', 'MLB', 'CIN', 'cin'),
  ('Cleveland Guardians', 'MLB', 'MLB', 'CLE', 'cle'),
  ('Colorado Rockies', 'MLB', 'MLB', 'COL', 'col'),
  ('Detroit Tigers', 'MLB', 'MLB', 'DET', 'det'),
  ('Houston Astros', 'MLB', 'MLB', 'HOU', 'hou'),
  ('Kansas City Royals', 'MLB', 'MLB', 'KC', 'kc'),
  ('Los Angeles Angels', 'MLB', 'MLB', 'LAA', 'laa'),
  ('Los Angeles Dodgers', 'MLB', 'MLB', 'LAD', 'lad'),
  ('Miami Marlins', 'MLB', 'MLB', 'MIA', 'mia'),
  ('Milwaukee Brewers', 'MLB', 'MLB', 'MIL', 'mil'),
  ('Minnesota Twins', 'MLB', 'MLB', 'MIN', 'min'),
  ('New York Mets', 'MLB', 'MLB', 'NYM', 'nym'),
  ('New York Yankees', 'MLB', 'MLB', 'NYY', 'nyy'),
  ('Athletics', 'MLB', 'MLB', 'ATH', 'ath'),
  ('Philadelphia Phillies', 'MLB', 'MLB', 'PHI', 'phi'),
  ('Pittsburgh Pirates', 'MLB', 'MLB', 'PIT', 'pit'),
  ('San Diego Padres', 'MLB', 'MLB', 'SD', 'sd'),
  ('San Francisco Giants', 'MLB', 'MLB', 'SF', 'sf'),
  ('Seattle Mariners', 'MLB', 'MLB', 'SEA', 'sea'),
  ('St. Louis Cardinals', 'MLB', 'MLB', 'STL', 'stl'),
  ('Tampa Bay Rays', 'MLB', 'MLB', 'TB', 'tb'),
  ('Texas Rangers', 'MLB', 'MLB', 'TEX', 'tex'),
  ('Toronto Blue Jays', 'MLB', 'MLB', 'TOR', 'tor'),
  ('Washington Nationals', 'MLB', 'MLB', 'WAS', 'was')
)
insert into public.teams (
  name,
  sport,
  league,
  abbreviation,
  provider_key
)
select
  supported.name,
  supported.sport,
  supported.league,
  supported.abbreviation,
  supported.provider_key
from supported_teams as supported
where not exists (
  select 1
  from public.teams as existing
  where lower(existing.name) = lower(supported.name)
);
