import type { RegisteredTeam } from "./teamRegistry";

export const MLS_REGISTERED_TEAMS: RegisteredTeam[] = [
   {
      routeKey: "mls-atl",
      teamId: "mls-atl",
      teamName: "Atlanta United FC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "atl",
      abbreviation: "ATL",
   },
   {
      routeKey: "mls-aus",
      teamId: "mls-aus",
      teamName: "Austin FC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "aus",
      abbreviation: "AUS",
   },
   {
      routeKey: "mls-clt",
      teamId: "mls-clt",
      teamName: "Charlotte FC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "clt",
      abbreviation: "CLT",
   },
   {
      routeKey: "mls-chi",
      teamId: "mls-chi",
      teamName: "Chicago Fire FC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "chi",
      abbreviation: "CHI",
   },
   {
      routeKey: "mls-cin",
      teamId: "mls-cin",
      teamName: "FC Cincinnati",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "cin",
      abbreviation: "CIN",
   },
   {
      routeKey: "mls-col",
      teamId: "mls-col",
      teamName: "Colorado Rapids",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "col",
      abbreviation: "COL",
   },
   {
      routeKey: "mls-clb",
      teamId: "mls-clb",
      teamName: "Columbus Crew",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "clb",
      abbreviation: "CLB",
   },
   {
      routeKey: "mls-dal",
      teamId: "mls-dal",
      teamName: "FC Dallas",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "dal",
      abbreviation: "DAL",
   },
   {
      routeKey: "mls-dc",
      teamId: "mls-dc",
      teamName: "D.C. United",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "dc",
      abbreviation: "DC",
   },
   {
      routeKey: "mls-hou",
      teamId: "mls-hou",
      teamName: "Houston Dynamo FC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "hou",
      abbreviation: "HOU",
   },
   {
      routeKey: "mls-skc",
      teamId: "mls-skc",
      teamName: "Sporting Kansas City",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "skc",
      abbreviation: "SKC",
   },
   {
      routeKey: "mls-lafc",
      teamId: "mls-lafc",
      teamName: "LAFC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "lafc",
      abbreviation: "LAFC",
   },
   {
      routeKey: "mls-lag",
      teamId: "mls-lag",
      teamName: "LA Galaxy",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "la",
      abbreviation: "LAG",
   },
   {
      routeKey: "mls-mia",
      teamId: "mls-mia",
      teamName: "Inter Miami CF",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "mia",
      abbreviation: "MIA",
   },
   {
      routeKey: "mls-min",
      teamId: "mls-min",
      teamName: "Minnesota United FC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "min",
      abbreviation: "MIN",
   },
   {
      routeKey: "mls-mtl",
      teamId: "mls-mtl",
      teamName: "CF Montréal",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "mtl",
      abbreviation: "MTL",
   },
   {
      routeKey: "mls-nsh",
      teamId: "mls-nsh",
      teamName: "Nashville SC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "nsh",
      abbreviation: "NSH",
   },
   {
      routeKey: "mls-ne",
      teamId: "mls-ne",
      teamName: "New England Revolution",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "ne",
      abbreviation: "NE",
   },
   {
      routeKey: "mls-nyc",
      teamId: "mls-nyc",
      teamName: "New York City FC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "nyc",
      abbreviation: "NYC",
   },
   {
      routeKey: "mls-nyrb",
      teamId: "mls-nyrb",
      teamName: "New York Red Bulls",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "ny",
      abbreviation: "NYRB",
   },
   {
      routeKey: "mls-orl",
      teamId: "mls-orl",
      teamName: "Orlando City SC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "orl",
      abbreviation: "ORL",
   },
   {
      routeKey: "mls-phi",
      teamId: "mls-phi",
      teamName: "Philadelphia Union",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "phi",
      abbreviation: "PHI",
   },
   {
      routeKey: "mls-por",
      teamId: "mls-por",
      teamName: "Portland Timbers",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "por",
      abbreviation: "POR",
   },
   {
      routeKey: "mls-rsl",
      teamId: "mls-rsl",
      teamName: "Real Salt Lake",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "rsl",
      abbreviation: "RSL",
   },
   {
      routeKey: "mls-sd",
      teamId: "mls-sd",
      teamName: "San Diego FC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "sd",
      abbreviation: "SD",
   },
   {
      routeKey: "mls-sj",
      teamId: "mls-sj",
      teamName: "San Jose Earthquakes",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "sj",
      abbreviation: "SJ",
   },
   {
      routeKey: "mls-sea",
      teamId: "mls-sea",
      teamName: "Seattle Sounders FC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "sea",
      abbreviation: "SEA",
   },
   {
      routeKey: "mls-stl",
      teamId: "mls-stl",
      teamName: "St. Louis CITY SC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "stl",
      abbreviation: "STL",
   },
   {
      routeKey: "mls-tor",
      teamId: "mls-tor",
      teamName: "Toronto FC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "tor",
      abbreviation: "TOR",
   },
   {
      routeKey: "mls-van",
      teamId: "mls-van",
      teamName: "Vancouver Whitecaps FC",
      sport: "SOCCER",
      league: "MLS",
      providerTeamKey: "van",
      abbreviation: "VAN",
   }
];
