import type { TeamAdapterInput } from "./types";
import { MLS_REGISTERED_TEAMS } from "./mlsRegisteredTeams";

export type RegisteredTeam = TeamAdapterInput & {
   routeKey: string;
   abbreviation?: string;
};

const REGISTERED_TEAMS: Record<string, RegisteredTeam> = {
   "nba-atl": {
      routeKey: "nba-atl",
      teamId: "nba-atl",
      teamName: "Atlanta Hawks",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "atl",
      abbreviation: "ATL",
   },
   "nba-bos": {
      routeKey: "nba-bos",
      teamId: "nba-bos",
      teamName: "Boston Celtics",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "bos",
      abbreviation: "BOS",
   },
   "nba-bkn": {
      routeKey: "nba-bkn",
      teamId: "nba-bkn",
      teamName: "Brooklyn Nets",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "bkn",
      abbreviation: "BKN",
   },
   "nba-cha": {
      routeKey: "nba-cha",
      teamId: "nba-cha",
      teamName: "Charlotte Hornets",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "cha",
      abbreviation: "CHA",
   },
   "nba-chi": {
      routeKey: "nba-chi",
      teamId: "nba-chi",
      teamName: "Chicago Bulls",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "chi",
      abbreviation: "CHI",
   },
   "nba-cle": {
      routeKey: "nba-cle",
      teamId: "nba-cle",
      teamName: "Cleveland Cavaliers",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "cle",
      abbreviation: "CLE",
   },
   "nba-dal": {
      routeKey: "nba-dal",
      teamId: "nba-dal",
      teamName: "Dallas Mavericks",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "dal",
      abbreviation: "DAL",
   },
   "nba-den": {
      routeKey: "nba-den",
      teamId: "nba-den",
      teamName: "Denver Nuggets",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "den",
      abbreviation: "DEN",
   },
   "nba-det": {
      routeKey: "nba-det",
      teamId: "nba-det",
      teamName: "Detroit Pistons",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "det",
      abbreviation: "DET",
   },
   "nba-gsw": {
      routeKey: "nba-gsw",
      teamId: "nba-gsw",
      teamName: "Golden State Warriors",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "gsw",
      abbreviation: "GSW",
   },
   "nba-hou": {
      routeKey: "nba-hou",
      teamId: "nba-hou",
      teamName: "Houston Rockets",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "hou",
      abbreviation: "HOU",
   },
   "nba-ind": {
      routeKey: "nba-ind",
      teamId: "nba-ind",
      teamName: "Indiana Pacers",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "ind",
      abbreviation: "IND",
   },
   "nba-lac": {
      routeKey: "nba-lac",
      teamId: "nba-lac",
      teamName: "LA Clippers",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "lac",
      abbreviation: "LAC",
   },
   "nba-lal": {
      routeKey: "nba-lal",
      teamId: "nba-lal",
      teamName: "Los Angeles Lakers",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "lal",
      abbreviation: "LAL",
   },
   "nba-mem": {
      routeKey: "nba-mem",
      teamId: "nba-mem",
      teamName: "Memphis Grizzlies",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "mem",
      abbreviation: "MEM",
   },
   "nba-mia": {
      routeKey: "nba-mia",
      teamId: "nba-mia",
      teamName: "Miami Heat",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "mia",
      abbreviation: "MIA",
   },
   "nba-mil": {
      routeKey: "nba-mil",
      teamId: "nba-mil",
      teamName: "Milwaukee Bucks",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "mil",
      abbreviation: "MIL",
   },
   "nba-min": {
      routeKey: "nba-min",
      teamId: "nba-min",
      teamName: "Minnesota Timberwolves",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "min",
      abbreviation: "MIN",
   },
   "nba-nop": {
      routeKey: "nba-nop",
      teamId: "nba-nop",
      teamName: "New Orleans Pelicans",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "nop",
      abbreviation: "NOP",
   },
   "nba-nyk": {
      routeKey: "nba-nyk",
      teamId: "nba-nyk",
      teamName: "New York Knicks",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "nyk",
      abbreviation: "NYK",
   },
   "nba-okc": {
      routeKey: "nba-okc",
      teamId: "nba-okc",
      teamName: "Oklahoma City Thunder",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "okc",
      abbreviation: "OKC",
   },
   "nba-orl": {
      routeKey: "nba-orl",
      teamId: "nba-orl",
      teamName: "Orlando Magic",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "orl",
      abbreviation: "ORL",
   },
   "nba-phi": {
      routeKey: "nba-phi",
      teamId: "nba-phi",
      teamName: "Philadelphia 76ers",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "phi",
      abbreviation: "PHI",
   },
   "nba-phx": {
      routeKey: "nba-phx",
      teamId: "nba-phx",
      teamName: "Phoenix Suns",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "phx",
      abbreviation: "PHX",
   },
   "nba-por": {
      routeKey: "nba-por",
      teamId: "nba-por",
      teamName: "Portland Trail Blazers",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "por",
      abbreviation: "POR",
   },
   "nba-sac": {
      routeKey: "nba-sac",
      teamId: "nba-sac",
      teamName: "Sacramento Kings",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "sac",
      abbreviation: "SAC",
   },
   "nba-sas": {
      routeKey: "nba-sas",
      teamId: "nba-sas",
      teamName: "San Antonio Spurs",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "sas",
      abbreviation: "SAS",
   },
   "nba-tor": {
      routeKey: "nba-tor",
      teamId: "nba-tor",
      teamName: "Toronto Raptors",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "tor",
      abbreviation: "TOR",
   },
   "nba-uta": {
      routeKey: "nba-uta",
      teamId: "nba-uta",
      teamName: "Utah Jazz",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "uta",
      abbreviation: "UTA",
   },
   "nba-was": {
      routeKey: "nba-was",
      teamId: "nba-was",
      teamName: "Washington Wizards",
      sport: "NBA",
      league: "NBA",
      providerTeamKey: "was",
      abbreviation: "WAS",
   },
   "nfl-ari": {
      routeKey: "nfl-ari",
      teamId: "nfl-ari",
      teamName: "Arizona Cardinals",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "ari",
      abbreviation: "ARI",
   },
   "nfl-atl": {
      routeKey: "nfl-atl",
      teamId: "nfl-atl",
      teamName: "Atlanta Falcons",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "atl",
      abbreviation: "ATL",
   },
   "nfl-bal": {
      routeKey: "nfl-bal",
      teamId: "nfl-bal",
      teamName: "Baltimore Ravens",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "bal",
      abbreviation: "BAL",
   },
   "nfl-buf": {
      routeKey: "nfl-buf",
      teamId: "nfl-buf",
      teamName: "Buffalo Bills",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "buf",
      abbreviation: "BUF",
   },
   "nfl-car": {
      routeKey: "nfl-car",
      teamId: "nfl-car",
      teamName: "Carolina Panthers",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "car",
      abbreviation: "CAR",
   },
   "nfl-chi": {
      routeKey: "nfl-chi",
      teamId: "nfl-chi",
      teamName: "Chicago Bears",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "chi",
      abbreviation: "CHI",
   },
   "nfl-cin": {
      routeKey: "nfl-cin",
      teamId: "nfl-cin",
      teamName: "Cincinnati Bengals",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "cin",
      abbreviation: "CIN",
   },
   "nfl-cle": {
      routeKey: "nfl-cle",
      teamId: "nfl-cle",
      teamName: "Cleveland Browns",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "cle",
      abbreviation: "CLE",
   },
   "nfl-dal": {
      routeKey: "nfl-dal",
      teamId: "nfl-dal",
      teamName: "Dallas Cowboys",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "dal",
      abbreviation: "DAL",
   },
   "nfl-den": {
      routeKey: "nfl-den",
      teamId: "nfl-den",
      teamName: "Denver Broncos",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "den",
      abbreviation: "DEN",
   },
   "nfl-det": {
      routeKey: "nfl-det",
      teamId: "nfl-det",
      teamName: "Detroit Lions",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "det",
      abbreviation: "DET",
   },
   "nfl-gb": {
      routeKey: "nfl-gb",
      teamId: "nfl-gb",
      teamName: "Green Bay Packers",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "gb",
      abbreviation: "GB",
   },
   "nfl-hou": {
      routeKey: "nfl-hou",
      teamId: "nfl-hou",
      teamName: "Houston Texans",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "hou",
      abbreviation: "HOU",
   },
   "nfl-ind": {
      routeKey: "nfl-ind",
      teamId: "nfl-ind",
      teamName: "Indianapolis Colts",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "ind",
      abbreviation: "IND",
   },
   "nfl-jax": {
      routeKey: "nfl-jax",
      teamId: "nfl-jax",
      teamName: "Jacksonville Jaguars",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "jax",
      abbreviation: "JAX",
   },
   "nfl-kc": {
      routeKey: "nfl-kc",
      teamId: "nfl-kc",
      teamName: "Kansas City Chiefs",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "kc",
      abbreviation: "KC",
   },
   "nfl-lv": {
      routeKey: "nfl-lv",
      teamId: "nfl-lv",
      teamName: "Las Vegas Raiders",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "lv",
      abbreviation: "LV",
   },
   "nfl-lac": {
      routeKey: "nfl-lac",
      teamId: "nfl-lac",
      teamName: "Los Angeles Chargers",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "lac",
      abbreviation: "LAC",
   },
   "nfl-lar": {
      routeKey: "nfl-lar",
      teamId: "nfl-lar",
      teamName: "Los Angeles Rams",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "lar",
      abbreviation: "LAR",
   },
   "nfl-mia": {
      routeKey: "nfl-mia",
      teamId: "nfl-mia",
      teamName: "Miami Dolphins",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "mia",
      abbreviation: "MIA",
   },
   "nfl-min": {
      routeKey: "nfl-min",
      teamId: "nfl-min",
      teamName: "Minnesota Vikings",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "min",
      abbreviation: "MIN",
   },
   "nfl-ne": {
      routeKey: "nfl-ne",
      teamId: "nfl-ne",
      teamName: "New England Patriots",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "ne",
      abbreviation: "NE",
   },
   "nfl-no": {
      routeKey: "nfl-no",
      teamId: "nfl-no",
      teamName: "New Orleans Saints",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "no",
      abbreviation: "NO",
   },
   "nfl-nyg": {
      routeKey: "nfl-nyg",
      teamId: "nfl-nyg",
      teamName: "New York Giants",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "nyg",
      abbreviation: "NYG",
   },
   "nfl-nyj": {
      routeKey: "nfl-nyj",
      teamId: "nfl-nyj",
      teamName: "New York Jets",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "nyj",
      abbreviation: "NYJ",
   },
   "nfl-phi": {
      routeKey: "nfl-phi",
      teamId: "nfl-phi",
      teamName: "Philadelphia Eagles",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "phi",
      abbreviation: "PHI",
   },
   "nfl-pit": {
      routeKey: "nfl-pit",
      teamId: "nfl-pit",
      teamName: "Pittsburgh Steelers",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "pit",
      abbreviation: "PIT",
   },
   "nfl-sf": {
      routeKey: "nfl-sf",
      teamId: "nfl-sf",
      teamName: "San Francisco 49ers",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "sf",
      abbreviation: "SF",
   },
   "nfl-sea": {
      routeKey: "nfl-sea",
      teamId: "nfl-sea",
      teamName: "Seattle Seahawks",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "sea",
      abbreviation: "SEA",
   },
   "nfl-tb": {
      routeKey: "nfl-tb",
      teamId: "nfl-tb",
      teamName: "Tampa Bay Buccaneers",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "tb",
      abbreviation: "TB",
   },
   "nfl-ten": {
      routeKey: "nfl-ten",
      teamId: "nfl-ten",
      teamName: "Tennessee Titans",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "ten",
      abbreviation: "TEN",
   },
   "nfl-was": {
      routeKey: "nfl-was",
      teamId: "nfl-was",
      teamName: "Washington Commanders",
      sport: "NFL",
      league: "NFL",
      providerTeamKey: "was",
      abbreviation: "WAS",
   },
   "epl-ars": {
      routeKey: "epl-ars",
      teamId: "epl-ars",
      teamName: "Arsenal",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "ars",
      abbreviation: "ARS",
   },
   "epl-avl": {
      routeKey: "epl-avl",
      teamId: "epl-avl",
      teamName: "Aston Villa",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "avl",
      abbreviation: "AVL",
   },
   "epl-bou": {
      routeKey: "epl-bou",
      teamId: "epl-bou",
      teamName: "Bournemouth",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "bou",
      abbreviation: "BOU",
   },
   "epl-bre": {
      routeKey: "epl-bre",
      teamId: "epl-bre",
      teamName: "Brentford",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "bre",
      abbreviation: "BRE",
   },
   "epl-bha": {
      routeKey: "epl-bha",
      teamId: "epl-bha",
      teamName: "Brighton & Hove Albion",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "bha",
      abbreviation: "BHA",
   },
   "epl-che": {
      routeKey: "epl-che",
      teamId: "epl-che",
      teamName: "Chelsea",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "che",
      abbreviation: "CHE",
   },
   "epl-cry": {
      routeKey: "epl-cry",
      teamId: "epl-cry",
      teamName: "Crystal Palace",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "cry",
      abbreviation: "CRY",
   },
   "epl-eve": {
      routeKey: "epl-eve",
      teamId: "epl-eve",
      teamName: "Everton",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "eve",
      abbreviation: "EVE",
   },
   "epl-ful": {
      routeKey: "epl-ful",
      teamId: "epl-ful",
      teamName: "Fulham",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "ful",
      abbreviation: "FUL",
   },
   "epl-liv": {
      routeKey: "epl-liv",
      teamId: "epl-liv",
      teamName: "Liverpool",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "liv",
      abbreviation: "LIV",
   },
   "epl-mci": {
      routeKey: "epl-mci",
      teamId: "epl-mci",
      teamName: "Manchester City",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "mci",
      abbreviation: "MCI",
   },
   "epl-mun": {
      routeKey: "epl-mun",
      teamId: "epl-mun",
      teamName: "Manchester United",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "mun",
      abbreviation: "MUN",
   },
   "epl-new": {
      routeKey: "epl-new",
      teamId: "epl-new",
      teamName: "Newcastle United",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "new",
      abbreviation: "NEW",
   },
   "epl-nfo": {
      routeKey: "epl-nfo",
      teamId: "epl-nfo",
      teamName: "Nottingham Forest",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "nfo",
      abbreviation: "NFO",
   },
   "epl-sun": {
      routeKey: "epl-sun",
      teamId: "epl-sun",
      teamName: "Sunderland",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "sun",
      abbreviation: "SUN",
   },
   "epl-tot": {
      routeKey: "epl-tot",
      teamId: "epl-tot",
      teamName: "Tottenham Hotspur",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "tot",
      abbreviation: "TOT",
   },
   "epl-whu": {
      routeKey: "epl-whu",
      teamId: "epl-whu",
      teamName: "West Ham United",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "whu",
      abbreviation: "WHU",
   },
   "epl-wol": {
      routeKey: "epl-wol",
      teamId: "epl-wol",
      teamName: "Wolverhampton Wanderers",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "wol",
      abbreviation: "WOL",
   },
   "epl-lee": {
      routeKey: "epl-lee",
      teamId: "epl-lee",
      teamName: "Leeds United",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "lee",
      abbreviation: "LEE",
   },
   "epl-bur": {
      routeKey: "epl-bur",
      teamId: "epl-bur",
      teamName: "Burnley",
      sport: "SOCCER",
      league: "Premier League",
      providerTeamKey: "bur",
      abbreviation: "BUR",
   },
   "mlb-ari": {
      routeKey: "mlb-ari",
      teamId: "mlb-ari",
      teamName: "Arizona Diamondbacks",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "ari",
      abbreviation: "ARI",
   },
   "mlb-atl": {
      routeKey: "mlb-atl",
      teamId: "mlb-atl",
      teamName: "Atlanta Braves",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "atl",
      abbreviation: "ATL",
   },
   "mlb-bal": {
      routeKey: "mlb-bal",
      teamId: "mlb-bal",
      teamName: "Baltimore Orioles",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "bal",
      abbreviation: "BAL",
   },
   "mlb-bos": {
      routeKey: "mlb-bos",
      teamId: "mlb-bos",
      teamName: "Boston Red Sox",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "bos",
      abbreviation: "BOS",
   },
   "mlb-chc": {
      routeKey: "mlb-chc",
      teamId: "mlb-chc",
      teamName: "Chicago Cubs",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "chc",
      abbreviation: "CHC",
   },
   "mlb-cws": {
      routeKey: "mlb-cws",
      teamId: "mlb-cws",
      teamName: "Chicago White Sox",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "cws",
      abbreviation: "CWS",
   },
   "mlb-cin": {
      routeKey: "mlb-cin",
      teamId: "mlb-cin",
      teamName: "Cincinnati Reds",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "cin",
      abbreviation: "CIN",
   },
   "mlb-cle": {
      routeKey: "mlb-cle",
      teamId: "mlb-cle",
      teamName: "Cleveland Guardians",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "cle",
      abbreviation: "CLE",
   },
   "mlb-col": {
      routeKey: "mlb-col",
      teamId: "mlb-col",
      teamName: "Colorado Rockies",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "col",
      abbreviation: "COL",
   },
   "mlb-det": {
      routeKey: "mlb-det",
      teamId: "mlb-det",
      teamName: "Detroit Tigers",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "det",
      abbreviation: "DET",
   },
   "mlb-hou": {
      routeKey: "mlb-hou",
      teamId: "mlb-hou",
      teamName: "Houston Astros",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "hou",
      abbreviation: "HOU",
   },
   "mlb-kc": {
      routeKey: "mlb-kc",
      teamId: "mlb-kc",
      teamName: "Kansas City Royals",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "kc",
      abbreviation: "KC",
   },
   "mlb-laa": {
      routeKey: "mlb-laa",
      teamId: "mlb-laa",
      teamName: "Los Angeles Angels",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "laa",
      abbreviation: "LAA",
   },
   "mlb-lad": {
      routeKey: "mlb-lad",
      teamId: "mlb-lad",
      teamName: "Los Angeles Dodgers",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "lad",
      abbreviation: "LAD",
   },
   "mlb-mia": {
      routeKey: "mlb-mia",
      teamId: "mlb-mia",
      teamName: "Miami Marlins",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "mia",
      abbreviation: "MIA",
   },
   "mlb-mil": {
      routeKey: "mlb-mil",
      teamId: "mlb-mil",
      teamName: "Milwaukee Brewers",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "mil",
      abbreviation: "MIL",
   },
   "mlb-min": {
      routeKey: "mlb-min",
      teamId: "mlb-min",
      teamName: "Minnesota Twins",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "min",
      abbreviation: "MIN",
   },
   "mlb-nym": {
      routeKey: "mlb-nym",
      teamId: "mlb-nym",
      teamName: "New York Mets",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "nym",
      abbreviation: "NYM",
   },
   "mlb-nyy": {
      routeKey: "mlb-nyy",
      teamId: "mlb-nyy",
      teamName: "New York Yankees",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "nyy",
      abbreviation: "NYY",
   },
   "mlb-ath": {
      routeKey: "mlb-ath",
      teamId: "mlb-ath",
      teamName: "Athletics",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "ath",
      abbreviation: "ATH",
   },
   "mlb-phi": {
      routeKey: "mlb-phi",
      teamId: "mlb-phi",
      teamName: "Philadelphia Phillies",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "phi",
      abbreviation: "PHI",
   },
   "mlb-pit": {
      routeKey: "mlb-pit",
      teamId: "mlb-pit",
      teamName: "Pittsburgh Pirates",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "pit",
      abbreviation: "PIT",
   },
   "mlb-sd": {
      routeKey: "mlb-sd",
      teamId: "mlb-sd",
      teamName: "San Diego Padres",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "sd",
      abbreviation: "SD",
   },
   "mlb-sf": {
      routeKey: "mlb-sf",
      teamId: "mlb-sf",
      teamName: "San Francisco Giants",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "sf",
      abbreviation: "SF",
   },
   "mlb-sea": {
      routeKey: "mlb-sea",
      teamId: "mlb-sea",
      teamName: "Seattle Mariners",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "sea",
      abbreviation: "SEA",
   },
   "mlb-stl": {
      routeKey: "mlb-stl",
      teamId: "mlb-stl",
      teamName: "St. Louis Cardinals",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "stl",
      abbreviation: "STL",
   },
   "mlb-tb": {
      routeKey: "mlb-tb",
      teamId: "mlb-tb",
      teamName: "Tampa Bay Rays",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "tb",
      abbreviation: "TB",
   },
   "mlb-tex": {
      routeKey: "mlb-tex",
      teamId: "mlb-tex",
      teamName: "Texas Rangers",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "tex",
      abbreviation: "TEX",
   },
   "mlb-tor": {
      routeKey: "mlb-tor",
      teamId: "mlb-tor",
      teamName: "Toronto Blue Jays",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "tor",
      abbreviation: "TOR",
   },
   "mlb-was": {
      routeKey: "mlb-was",
      teamId: "mlb-was",
      teamName: "Washington Nationals",
      sport: "MLB",
      league: "MLB",
      providerTeamKey: "was",
      abbreviation: "WAS",
   },
};

Object.assign(REGISTERED_TEAMS, Object.fromEntries(MLS_REGISTERED_TEAMS.map((team) => [team.routeKey, team])));

const ROUTE_KEY_BY_TEAM_NAME = new Map(Object.values(REGISTERED_TEAMS).map((team) => [team.teamName.toLowerCase(), team.routeKey]));

export function getRegisteredTeam(identifier: string) {
   const normalizedIdentifier = identifier.toLowerCase();

   const directMatch = REGISTERED_TEAMS[normalizedIdentifier];

   if (directMatch) {
      return directMatch;
   }

   return Object.values(REGISTERED_TEAMS).find((team) => {
      return team.providerTeamKey?.toLowerCase() === normalizedIdentifier || team.abbreviation?.toLowerCase() === normalizedIdentifier || team.teamName.toLowerCase() === normalizedIdentifier;
   });
}

export function getRouteKeyByTeamName(teamName: string) {
   return ROUTE_KEY_BY_TEAM_NAME.get(teamName.toLowerCase());
}

export function listRegisteredTeams() {
   return Object.values(REGISTERED_TEAMS);
}
